### ISSUE TITLE
Add open pullrequest button

### ISSUE THREAD

**Issue by aukehuizinga** [ehamiter/GitHubinator#67]
It would be really nice to have an "open pullrequest" button also.

**Comment by chdsbd** [comment]
@ehamiter Would you be willing to merge a PR (I could make it) that adds this feature?

**Comment by ehamiter** [comment]
That seems outside the scope of what this plugin does-- namely, opening a github page that shows highlighted lines. It just seems like it would be tacking on other features that don't have anything to do with this. Currently this plugin supports Bitbucket as well, so that would need to be taken into account. I'm leaning toward "no" unless a lot of people would agree it would make a good fit. I think it would be fine as a standalone plugin, though, if you're up for creating one.

**Comment by JGJP** [comment]
I think having a "show highlighted lines in pull request Files Changed tab" feature would be super useful for reviews. Not sure how doable it is.

Supporting Bitbucket is weird considering the name of this plugin.
